#include <time.h>
#include <stdio.h>
#include <limits.h>


/*  What is the max time that can be generated by the time tunction?
 */
int main(){
    time_t test = UINT_MAX;

    printf("Max time_t value as seconds:        %lu\n", (unsigned long)test);
    printf("Max time_t value as a day / year:   %s\n", ctime(&test));

    time_t now = time(NULL);
    printf("Current Day as seconds:             %lu\n", (unsigned long)now);
    printf("Current Day as day / year:          %s\n", ctime(&now));

    printf("Seconds difference between the two: %lf\n", difftime(test, now));
}
